[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "librezip"
version = "0.1.0"

[dependencies]
bit-vec = "0.4.4"
error-chain = "0.11.0"
itertools = "0.6.3"
lazy_static = "0.2.8"
[profile.release]
debug = true
lto = true
