[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "rezippers"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
clap = "2"
hash-roll = "0.2"


[dependencies.flate2]
version = "1"
features = ["rust_backend"]
default-features = false

[dependencies.librezip]
path = "../lib"
